[package]
name = "josh-sync"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }
directories = "6"
regex = "1.12.3"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
urlencoding = "2"
which = "8"

[profile.release]
debug = "line-tables-only"
